/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as AdminVisitorsRouteImport } from './routes/admin/visitors'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRateLimitsRouteImport } from './routes/admin/rate-limits'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminKitchenSinkRouteImport } from './routes/admin/kitchen-sink'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRateLimitsRoute = AdminRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenSinkRoute = AdminKitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/login': typeof AuthLoginRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kitchen-sink': typeof AdminKitchenSinkRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/login': typeof AuthLoginRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kitchen-sink': typeof AdminKitchenSinkRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kitchen-sink': typeof AdminKitchenSinkRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/onboarding'
    | '/setup'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/kitchen-sink'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/admin/visitors'
    | '/payment/success'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/onboarding'
    | '/setup'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/kitchen-sink'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/admin/visitors'
    | '/payment/success'
    | '/admin'
  id:
    | '__root__'
    | '/_protected'
    | '/accept-invitation'
    | '/admin'
    | '/onboarding'
    | '/setup'
    | '/_auth/login'
    | '/_protected/account'
    | '/_protected/dashboard'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/kitchen-sink'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/admin/visitors'
    | '/payment/success'
    | '/_public/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SetupRoute: typeof SetupRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rate-limits': {
      id: '/admin/rate-limits'
      path: '/rate-limits'
      fullPath: '/admin/rate-limits'
      preLoaderRoute: typeof AdminRateLimitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen-sink': {
      id: '/admin/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/admin/kitchen-sink'
      preLoaderRoute: typeof AdminKitchenSinkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminKitchenSinkRoute: typeof AdminKitchenSinkRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminRateLimitsRoute: typeof AdminRateLimitsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminKitchenSinkRoute: AdminKitchenSinkRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminRateLimitsRoute: AdminRateLimitsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SetupRoute: SetupRoute,
  AuthLoginRoute: AuthLoginRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
