import { describe, expect, it } from "bun:test";
import { AllPermissions, Permissions, RolePermissionMap, Roles } from "@rbac";

describe("ecommerce permissions", () => {
  it("adds ecommerce permissions to the catalog", () => {
    expect(AllPermissions).toContain(Permissions.AdminCatalogRead);
    expect(AllPermissions).toContain(Permissions.AdminCatalogManage);
    expect(AllPermissions).toContain(Permissions.AdminProductsRead);
    expect(AllPermissions).toContain(Permissions.AdminProductsManage);
    expect(AllPermissions).toContain(Permissions.AdminInventoryRead);
    expect(AllPermissions).toContain(Permissions.AdminInventoryManage);
    expect(AllPermissions).toContain(Permissions.AdminOrdersRead);
    expect(AllPermissions).toContain(Permissions.AdminOrdersManage);
    expect(AllPermissions).toContain(Permissions.AdminOrdersFulfill);
    expect(AllPermissions).toContain(Permissions.AdminOrdersCancel);
    expect(AllPermissions).toContain(Permissions.AdminOrdersRefund);
    expect(AllPermissions).toContain(Permissions.AdminImagesRead);
    expect(AllPermissions).toContain(Permissions.AdminImagesManage);
    expect(AllPermissions).toContain(Permissions.AdminShippingRead);
    expect(AllPermissions).toContain(Permissions.AdminShippingManage);
    expect(AllPermissions).toContain(Permissions.AdminDiscountsRead);
    expect(AllPermissions).toContain(Permissions.AdminDiscountsManage);
    expect(AllPermissions).toContain(Permissions.AdminStoreSettingsRead);
    expect(AllPermissions).toContain(Permissions.AdminStoreSettingsManage);
  });

  it("grants ecommerce permissions to owner and admin, not platform user", () => {
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(
      Permissions.AdminCatalogManage,
    );
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(
      Permissions.AdminProductsManage,
    );
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(
      Permissions.AdminInventoryManage,
    );
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(
      Permissions.AdminOrdersManage,
    );
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(
      Permissions.AdminOrdersFulfill,
    );
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(
      Permissions.AdminOrdersCancel,
    );
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(
      Permissions.AdminOrdersRefund,
    );
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(
      Permissions.AdminImagesManage,
    );
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(Permissions.AdminShippingManage);
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(Permissions.AdminDiscountsManage);
    expect(RolePermissionMap[Roles.PlatformOwner]).toContain(Permissions.AdminStoreSettingsManage);
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(
      Permissions.AdminCatalogManage,
    );
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(
      Permissions.AdminProductsManage,
    );
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(
      Permissions.AdminInventoryManage,
    );
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(
      Permissions.AdminOrdersManage,
    );
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(
      Permissions.AdminOrdersFulfill,
    );
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(
      Permissions.AdminOrdersCancel,
    );
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(
      Permissions.AdminOrdersRefund,
    );
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(
      Permissions.AdminImagesManage,
    );
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(Permissions.AdminShippingManage);
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(Permissions.AdminDiscountsManage);
    expect(RolePermissionMap[Roles.PlatformAdmin]).toContain(Permissions.AdminStoreSettingsManage);
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(
      Permissions.AdminCatalogRead,
    );
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(
      Permissions.AdminProductsRead,
    );
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(
      Permissions.AdminInventoryRead,
    );
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(
      Permissions.AdminOrdersRead,
    );
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(
      Permissions.AdminOrdersFulfill,
    );
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(
      Permissions.AdminOrdersCancel,
    );
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(
      Permissions.AdminOrdersRefund,
    );
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(
      Permissions.AdminImagesRead,
    );
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(Permissions.AdminShippingRead);
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(Permissions.AdminDiscountsRead);
    expect(RolePermissionMap[Roles.PlatformUser]).not.toContain(Permissions.AdminStoreSettingsRead);
  });
});
